// Code generated by thriftgo (0.4.1). DO NOT EDIT.

package course

import (
	"LiveLive/kitex_gen/livelive/base"
	"context"
	"fmt"
)

type CreateCourseReq struct {
	Classname   string `thrift:"classname,1" frugal:"1,default,string" json:"classname"`
	Description string `thrift:"description,2" frugal:"2,default,string" json:"description"`
	TeacherId   int64  `thrift:"teacher_id,3" frugal:"3,default,i64" json:"teacher_id"`
}

func NewCreateCourseReq() *CreateCourseReq {
	return &CreateCourseReq{}
}

func (p *CreateCourseReq) InitDefault() {
}

func (p *CreateCourseReq) GetClassname() (v string) {
	return p.Classname
}

func (p *CreateCourseReq) GetDescription() (v string) {
	return p.Description
}

func (p *CreateCourseReq) GetTeacherId() (v int64) {
	return p.TeacherId
}
func (p *CreateCourseReq) SetClassname(val string) {
	p.Classname = val
}
func (p *CreateCourseReq) SetDescription(val string) {
	p.Description = val
}
func (p *CreateCourseReq) SetTeacherId(val int64) {
	p.TeacherId = val
}

func (p *CreateCourseReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CreateCourseReq(%+v)", *p)
}

var fieldIDToName_CreateCourseReq = map[int16]string{
	1: "classname",
	2: "description",
	3: "teacher_id",
}

type CreateCourseResp struct {
	BaseResp *base.BaseResp `thrift:"baseResp,255" frugal:"255,default,base.BaseResp" json:"baseResp"`
}

func NewCreateCourseResp() *CreateCourseResp {
	return &CreateCourseResp{}
}

func (p *CreateCourseResp) InitDefault() {
}

var CreateCourseResp_BaseResp_DEFAULT *base.BaseResp

func (p *CreateCourseResp) GetBaseResp() (v *base.BaseResp) {
	if !p.IsSetBaseResp() {
		return CreateCourseResp_BaseResp_DEFAULT
	}
	return p.BaseResp
}
func (p *CreateCourseResp) SetBaseResp(val *base.BaseResp) {
	p.BaseResp = val
}

func (p *CreateCourseResp) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *CreateCourseResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CreateCourseResp(%+v)", *p)
}

var fieldIDToName_CreateCourseResp = map[int16]string{
	255: "baseResp",
}

type JoinCourseReq struct {
	StudentId      int64  `thrift:"student_id,1" frugal:"1,default,i64" json:"student_id"`
	Classname      string `thrift:"classname,2" frugal:"2,default,string" json:"classname"`
	InvitationCode string `thrift:"invitation_code,3" frugal:"3,default,string" json:"invitation_code"`
	TeacherName    string `thrift:"teacher_name,4" frugal:"4,default,string" json:"teacher_name"`
	StudentName    string `thrift:"student_name,5" frugal:"5,default,string" json:"student_name"`
}

func NewJoinCourseReq() *JoinCourseReq {
	return &JoinCourseReq{}
}

func (p *JoinCourseReq) InitDefault() {
}

func (p *JoinCourseReq) GetStudentId() (v int64) {
	return p.StudentId
}

func (p *JoinCourseReq) GetClassname() (v string) {
	return p.Classname
}

func (p *JoinCourseReq) GetInvitationCode() (v string) {
	return p.InvitationCode
}

func (p *JoinCourseReq) GetTeacherName() (v string) {
	return p.TeacherName
}

func (p *JoinCourseReq) GetStudentName() (v string) {
	return p.StudentName
}
func (p *JoinCourseReq) SetStudentId(val int64) {
	p.StudentId = val
}
func (p *JoinCourseReq) SetClassname(val string) {
	p.Classname = val
}
func (p *JoinCourseReq) SetInvitationCode(val string) {
	p.InvitationCode = val
}
func (p *JoinCourseReq) SetTeacherName(val string) {
	p.TeacherName = val
}
func (p *JoinCourseReq) SetStudentName(val string) {
	p.StudentName = val
}

func (p *JoinCourseReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("JoinCourseReq(%+v)", *p)
}

var fieldIDToName_JoinCourseReq = map[int16]string{
	1: "student_id",
	2: "classname",
	3: "invitation_code",
	4: "teacher_name",
	5: "student_name",
}

type JoinCourseResp struct {
	BaseResp *base.BaseResp `thrift:"baseResp,255" frugal:"255,default,base.BaseResp" json:"baseResp"`
}

func NewJoinCourseResp() *JoinCourseResp {
	return &JoinCourseResp{}
}

func (p *JoinCourseResp) InitDefault() {
}

var JoinCourseResp_BaseResp_DEFAULT *base.BaseResp

func (p *JoinCourseResp) GetBaseResp() (v *base.BaseResp) {
	if !p.IsSetBaseResp() {
		return JoinCourseResp_BaseResp_DEFAULT
	}
	return p.BaseResp
}
func (p *JoinCourseResp) SetBaseResp(val *base.BaseResp) {
	p.BaseResp = val
}

func (p *JoinCourseResp) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *JoinCourseResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("JoinCourseResp(%+v)", *p)
}

var fieldIDToName_JoinCourseResp = map[int16]string{
	255: "baseResp",
}

type CreateCourseInviteReq struct {
	Classname  string `thrift:"classname,1" frugal:"1,default,string" json:"classname"`
	MaxUsage   int64  `thrift:"max_usage,2" frugal:"2,default,i64" json:"max_usage"`
	UsageCount int64  `thrift:"usage_count,3" frugal:"3,default,i64" json:"usage_count"`
	ExpiredAt  int64  `thrift:"expired_at,4" frugal:"4,default,i64" json:"expired_at"`
	TeacherId  int64  `thrift:"teacher_id,5" frugal:"5,default,i64" json:"teacher_id"`
}

func NewCreateCourseInviteReq() *CreateCourseInviteReq {
	return &CreateCourseInviteReq{}
}

func (p *CreateCourseInviteReq) InitDefault() {
}

func (p *CreateCourseInviteReq) GetClassname() (v string) {
	return p.Classname
}

func (p *CreateCourseInviteReq) GetMaxUsage() (v int64) {
	return p.MaxUsage
}

func (p *CreateCourseInviteReq) GetUsageCount() (v int64) {
	return p.UsageCount
}

func (p *CreateCourseInviteReq) GetExpiredAt() (v int64) {
	return p.ExpiredAt
}

func (p *CreateCourseInviteReq) GetTeacherId() (v int64) {
	return p.TeacherId
}
func (p *CreateCourseInviteReq) SetClassname(val string) {
	p.Classname = val
}
func (p *CreateCourseInviteReq) SetMaxUsage(val int64) {
	p.MaxUsage = val
}
func (p *CreateCourseInviteReq) SetUsageCount(val int64) {
	p.UsageCount = val
}
func (p *CreateCourseInviteReq) SetExpiredAt(val int64) {
	p.ExpiredAt = val
}
func (p *CreateCourseInviteReq) SetTeacherId(val int64) {
	p.TeacherId = val
}

func (p *CreateCourseInviteReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CreateCourseInviteReq(%+v)", *p)
}

var fieldIDToName_CreateCourseInviteReq = map[int16]string{
	1: "classname",
	2: "max_usage",
	3: "usage_count",
	4: "expired_at",
	5: "teacher_id",
}

type CreateCourseInviteResp struct {
	InviteCode string         `thrift:"invite_code,1" frugal:"1,default,string" json:"invite_code"`
	BaseResp   *base.BaseResp `thrift:"baseResp,255" frugal:"255,default,base.BaseResp" json:"baseResp"`
}

func NewCreateCourseInviteResp() *CreateCourseInviteResp {
	return &CreateCourseInviteResp{}
}

func (p *CreateCourseInviteResp) InitDefault() {
}

func (p *CreateCourseInviteResp) GetInviteCode() (v string) {
	return p.InviteCode
}

var CreateCourseInviteResp_BaseResp_DEFAULT *base.BaseResp

func (p *CreateCourseInviteResp) GetBaseResp() (v *base.BaseResp) {
	if !p.IsSetBaseResp() {
		return CreateCourseInviteResp_BaseResp_DEFAULT
	}
	return p.BaseResp
}
func (p *CreateCourseInviteResp) SetInviteCode(val string) {
	p.InviteCode = val
}
func (p *CreateCourseInviteResp) SetBaseResp(val *base.BaseResp) {
	p.BaseResp = val
}

func (p *CreateCourseInviteResp) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *CreateCourseInviteResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CreateCourseInviteResp(%+v)", *p)
}

var fieldIDToName_CreateCourseInviteResp = map[int16]string{
	1:   "invite_code",
	255: "baseResp",
}

type CourseService interface {
	CreateCourse(ctx context.Context, req *CreateCourseReq) (r *CreateCourseResp, err error)

	JoinCourse(ctx context.Context, req *JoinCourseReq) (r *JoinCourseResp, err error)

	CreateCourseInvite(ctx context.Context, req *CreateCourseInviteReq) (r *CreateCourseInviteResp, err error)
}

type CourseServiceCreateCourseArgs struct {
	Req *CreateCourseReq `thrift:"req,1" frugal:"1,default,CreateCourseReq" json:"req"`
}

func NewCourseServiceCreateCourseArgs() *CourseServiceCreateCourseArgs {
	return &CourseServiceCreateCourseArgs{}
}

func (p *CourseServiceCreateCourseArgs) InitDefault() {
}

var CourseServiceCreateCourseArgs_Req_DEFAULT *CreateCourseReq

func (p *CourseServiceCreateCourseArgs) GetReq() (v *CreateCourseReq) {
	if !p.IsSetReq() {
		return CourseServiceCreateCourseArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *CourseServiceCreateCourseArgs) SetReq(val *CreateCourseReq) {
	p.Req = val
}

func (p *CourseServiceCreateCourseArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *CourseServiceCreateCourseArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CourseServiceCreateCourseArgs(%+v)", *p)
}

var fieldIDToName_CourseServiceCreateCourseArgs = map[int16]string{
	1: "req",
}

type CourseServiceCreateCourseResult struct {
	Success *CreateCourseResp `thrift:"success,0,optional" frugal:"0,optional,CreateCourseResp" json:"success,omitempty"`
}

func NewCourseServiceCreateCourseResult() *CourseServiceCreateCourseResult {
	return &CourseServiceCreateCourseResult{}
}

func (p *CourseServiceCreateCourseResult) InitDefault() {
}

var CourseServiceCreateCourseResult_Success_DEFAULT *CreateCourseResp

func (p *CourseServiceCreateCourseResult) GetSuccess() (v *CreateCourseResp) {
	if !p.IsSetSuccess() {
		return CourseServiceCreateCourseResult_Success_DEFAULT
	}
	return p.Success
}
func (p *CourseServiceCreateCourseResult) SetSuccess(x interface{}) {
	p.Success = x.(*CreateCourseResp)
}

func (p *CourseServiceCreateCourseResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *CourseServiceCreateCourseResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CourseServiceCreateCourseResult(%+v)", *p)
}

var fieldIDToName_CourseServiceCreateCourseResult = map[int16]string{
	0: "success",
}

type CourseServiceJoinCourseArgs struct {
	Req *JoinCourseReq `thrift:"req,1" frugal:"1,default,JoinCourseReq" json:"req"`
}

func NewCourseServiceJoinCourseArgs() *CourseServiceJoinCourseArgs {
	return &CourseServiceJoinCourseArgs{}
}

func (p *CourseServiceJoinCourseArgs) InitDefault() {
}

var CourseServiceJoinCourseArgs_Req_DEFAULT *JoinCourseReq

func (p *CourseServiceJoinCourseArgs) GetReq() (v *JoinCourseReq) {
	if !p.IsSetReq() {
		return CourseServiceJoinCourseArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *CourseServiceJoinCourseArgs) SetReq(val *JoinCourseReq) {
	p.Req = val
}

func (p *CourseServiceJoinCourseArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *CourseServiceJoinCourseArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CourseServiceJoinCourseArgs(%+v)", *p)
}

var fieldIDToName_CourseServiceJoinCourseArgs = map[int16]string{
	1: "req",
}

type CourseServiceJoinCourseResult struct {
	Success *JoinCourseResp `thrift:"success,0,optional" frugal:"0,optional,JoinCourseResp" json:"success,omitempty"`
}

func NewCourseServiceJoinCourseResult() *CourseServiceJoinCourseResult {
	return &CourseServiceJoinCourseResult{}
}

func (p *CourseServiceJoinCourseResult) InitDefault() {
}

var CourseServiceJoinCourseResult_Success_DEFAULT *JoinCourseResp

func (p *CourseServiceJoinCourseResult) GetSuccess() (v *JoinCourseResp) {
	if !p.IsSetSuccess() {
		return CourseServiceJoinCourseResult_Success_DEFAULT
	}
	return p.Success
}
func (p *CourseServiceJoinCourseResult) SetSuccess(x interface{}) {
	p.Success = x.(*JoinCourseResp)
}

func (p *CourseServiceJoinCourseResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *CourseServiceJoinCourseResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CourseServiceJoinCourseResult(%+v)", *p)
}

var fieldIDToName_CourseServiceJoinCourseResult = map[int16]string{
	0: "success",
}

type CourseServiceCreateCourseInviteArgs struct {
	Req *CreateCourseInviteReq `thrift:"req,1" frugal:"1,default,CreateCourseInviteReq" json:"req"`
}

func NewCourseServiceCreateCourseInviteArgs() *CourseServiceCreateCourseInviteArgs {
	return &CourseServiceCreateCourseInviteArgs{}
}

func (p *CourseServiceCreateCourseInviteArgs) InitDefault() {
}

var CourseServiceCreateCourseInviteArgs_Req_DEFAULT *CreateCourseInviteReq

func (p *CourseServiceCreateCourseInviteArgs) GetReq() (v *CreateCourseInviteReq) {
	if !p.IsSetReq() {
		return CourseServiceCreateCourseInviteArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *CourseServiceCreateCourseInviteArgs) SetReq(val *CreateCourseInviteReq) {
	p.Req = val
}

func (p *CourseServiceCreateCourseInviteArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *CourseServiceCreateCourseInviteArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CourseServiceCreateCourseInviteArgs(%+v)", *p)
}

var fieldIDToName_CourseServiceCreateCourseInviteArgs = map[int16]string{
	1: "req",
}

type CourseServiceCreateCourseInviteResult struct {
	Success *CreateCourseInviteResp `thrift:"success,0,optional" frugal:"0,optional,CreateCourseInviteResp" json:"success,omitempty"`
}

func NewCourseServiceCreateCourseInviteResult() *CourseServiceCreateCourseInviteResult {
	return &CourseServiceCreateCourseInviteResult{}
}

func (p *CourseServiceCreateCourseInviteResult) InitDefault() {
}

var CourseServiceCreateCourseInviteResult_Success_DEFAULT *CreateCourseInviteResp

func (p *CourseServiceCreateCourseInviteResult) GetSuccess() (v *CreateCourseInviteResp) {
	if !p.IsSetSuccess() {
		return CourseServiceCreateCourseInviteResult_Success_DEFAULT
	}
	return p.Success
}
func (p *CourseServiceCreateCourseInviteResult) SetSuccess(x interface{}) {
	p.Success = x.(*CreateCourseInviteResp)
}

func (p *CourseServiceCreateCourseInviteResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *CourseServiceCreateCourseInviteResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CourseServiceCreateCourseInviteResult(%+v)", *p)
}

var fieldIDToName_CourseServiceCreateCourseInviteResult = map[int16]string{
	0: "success",
}
