version: '3.9'

services:
  mysql:
    image: mysql:8.0
    container_name: livelive-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: livelive
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  redis:
    image: redis:7
    container_name: livelive-redis
    restart: always
    ports:
      - "6379:6379"

  zookeeper:
    image: wurstmeister/zookeeper:3.4
    container_name: livelive-zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:2.13-2.8.0
    container_name: livelive-kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper

  etcd:
    image: quay.io/coreos/etcd:v3.3
    container_name: livelive-etcd
    environment:
      ETCD_NAME: livelive-etcd
      ETCD_DATA_DIR: /etcd-data
      ETCD_ADVERTISE_CLIENT_URLS: http://0.0.0.0:2379
      ETCD_LISTEN_CLIENT_URLS: http://0.0.0.0:2379
    ports:
      - "2379:2379"

  livego:
    image: gwuhaolin/livego
    container_name: livelive-livego
    ports:
      - "1935:1935"    # RTMP 推流端口
      - "7001:7001"    # HTTP-FLV 播放端口
      - "8090:8090"    # LiveGo Web 界面
    command: ["./livego"]

volumes:
  mysql-data:
