// Code generated by Kitex v0.13.1. DO NOT EDIT.

package courseservice

import (
	course "LiveLive/kitex_gen/livelive/course"
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	CreateCourse(ctx context.Context, req *course.CreateCourseReq, callOptions ...callopt.Option) (r *course.CreateCourseResp, err error)
	JoinCourse(ctx context.Context, req *course.JoinCourseReq, callOptions ...callopt.Option) (r *course.JoinCourseResp, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kCourseServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kCourseServiceClient struct {
	*kClient
}

func (p *kCourseServiceClient) CreateCourse(ctx context.Context, req *course.CreateCourseReq, callOptions ...callopt.Option) (r *course.CreateCourseResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CreateCourse(ctx, req)
}

func (p *kCourseServiceClient) JoinCourse(ctx context.Context, req *course.JoinCourseReq, callOptions ...callopt.Option) (r *course.JoinCourseResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.JoinCourse(ctx, req)
}
