// Code generated by Kitex v0.13.1. DO NOT EDIT.

package courseservice

import (
	course "LiveLive/kitex_gen/livelive/course"
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"CreateCourse": kitex.NewMethodInfo(
		createCourseHandler,
		newCourseServiceCreateCourseArgs,
		newCourseServiceCreateCourseResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"JoinCourse": kitex.NewMethodInfo(
		joinCourseHandler,
		newCourseServiceJoinCourseArgs,
		newCourseServiceJoinCourseResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	courseServiceServiceInfo                = NewServiceInfo()
	courseServiceServiceInfoForClient       = NewServiceInfoForClient()
	courseServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return courseServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return courseServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return courseServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "CourseService"
	handlerType := (*course.CourseService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "course",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.13.1",
		Extra:           extra,
	}
	return svcInfo
}

func createCourseHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*course.CourseServiceCreateCourseArgs)
	realResult := result.(*course.CourseServiceCreateCourseResult)
	success, err := handler.(course.CourseService).CreateCourse(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newCourseServiceCreateCourseArgs() interface{} {
	return course.NewCourseServiceCreateCourseArgs()
}

func newCourseServiceCreateCourseResult() interface{} {
	return course.NewCourseServiceCreateCourseResult()
}

func joinCourseHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*course.CourseServiceJoinCourseArgs)
	realResult := result.(*course.CourseServiceJoinCourseResult)
	success, err := handler.(course.CourseService).JoinCourse(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newCourseServiceJoinCourseArgs() interface{} {
	return course.NewCourseServiceJoinCourseArgs()
}

func newCourseServiceJoinCourseResult() interface{} {
	return course.NewCourseServiceJoinCourseResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) CreateCourse(ctx context.Context, req *course.CreateCourseReq) (r *course.CreateCourseResp, err error) {
	var _args course.CourseServiceCreateCourseArgs
	_args.Req = req
	var _result course.CourseServiceCreateCourseResult
	if err = p.c.Call(ctx, "CreateCourse", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) JoinCourse(ctx context.Context, req *course.JoinCourseReq) (r *course.JoinCourseResp, err error) {
	var _args course.CourseServiceJoinCourseArgs
	_args.Req = req
	var _result course.CourseServiceJoinCourseResult
	if err = p.c.Call(ctx, "JoinCourse", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
