// Code generated by Kitex v0.13.1. DO NOT EDIT.

package quizservice

import (
	quiz "LiveLive/kitex_gen/livelive/quiz"
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	PublishChoiceQuestion(ctx context.Context, req *quiz.PublishChoiceQuestionReq, callOptions ...callopt.Option) (r *quiz.PublishChoiceQuestionResp, err error)
	PublishTrueOrFalseQuestion(ctx context.Context, req *quiz.PublishTrueOrFalseQuestionReq, callOptions ...callopt.Option) (r *quiz.PublishTrueOrFalseQuestionResp, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kQuizServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kQuizServiceClient struct {
	*kClient
}

func (p *kQuizServiceClient) PublishChoiceQuestion(ctx context.Context, req *quiz.PublishChoiceQuestionReq, callOptions ...callopt.Option) (r *quiz.PublishChoiceQuestionResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.PublishChoiceQuestion(ctx, req)
}

func (p *kQuizServiceClient) PublishTrueOrFalseQuestion(ctx context.Context, req *quiz.PublishTrueOrFalseQuestionReq, callOptions ...callopt.Option) (r *quiz.PublishTrueOrFalseQuestionResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.PublishTrueOrFalseQuestion(ctx, req)
}
