// Code generated by Kitex v0.13.1. DO NOT EDIT.

package quizservice

import (
	quiz "LiveLive/kitex_gen/livelive/quiz"
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"PublishChoiceQuestion": kitex.NewMethodInfo(
		publishChoiceQuestionHandler,
		newQuizServicePublishChoiceQuestionArgs,
		newQuizServicePublishChoiceQuestionResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	quizServiceServiceInfo                = NewServiceInfo()
	quizServiceServiceInfoForClient       = NewServiceInfoForClient()
	quizServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return quizServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return quizServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return quizServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "QuizService"
	handlerType := (*quiz.QuizService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "quiz",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.13.1",
		Extra:           extra,
	}
	return svcInfo
}

func publishChoiceQuestionHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*quiz.QuizServicePublishChoiceQuestionArgs)
	realResult := result.(*quiz.QuizServicePublishChoiceQuestionResult)
	success, err := handler.(quiz.QuizService).PublishChoiceQuestion(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newQuizServicePublishChoiceQuestionArgs() interface{} {
	return quiz.NewQuizServicePublishChoiceQuestionArgs()
}

func newQuizServicePublishChoiceQuestionResult() interface{} {
	return quiz.NewQuizServicePublishChoiceQuestionResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) PublishChoiceQuestion(ctx context.Context, req *quiz.PublishChoiceQuestionReq) (r *quiz.PublishChoiceQuestionResp, err error) {
	var _args quiz.QuizServicePublishChoiceQuestionArgs
	_args.Req = req
	var _result quiz.QuizServicePublishChoiceQuestionResult
	if err = p.c.Call(ctx, "PublishChoiceQuestion", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
