// Code generated by Kitex v0.13.1. DO NOT EDIT.

package liveservice

import (
	live "LiveLive/kitex_gen/livelive/live"
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"GetStreamKey": kitex.NewMethodInfo(
		getStreamKeyHandler,
		newLiveServiceGetStreamKeyArgs,
		newLiveServiceGetStreamKeyResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	liveServiceServiceInfo                = NewServiceInfo()
	liveServiceServiceInfoForClient       = NewServiceInfoForClient()
	liveServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return liveServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return liveServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return liveServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "LiveService"
	handlerType := (*live.LiveService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "live",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.13.1",
		Extra:           extra,
	}
	return svcInfo
}

func getStreamKeyHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*live.LiveServiceGetStreamKeyArgs)
	realResult := result.(*live.LiveServiceGetStreamKeyResult)
	success, err := handler.(live.LiveService).GetStreamKey(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newLiveServiceGetStreamKeyArgs() interface{} {
	return live.NewLiveServiceGetStreamKeyArgs()
}

func newLiveServiceGetStreamKeyResult() interface{} {
	return live.NewLiveServiceGetStreamKeyResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) GetStreamKey(ctx context.Context, req *live.GetStreamKeyReq) (r *live.GetStreamKeyResp, err error) {
	var _args live.LiveServiceGetStreamKeyArgs
	_args.Req = req
	var _result live.LiveServiceGetStreamKeyResult
	if err = p.c.Call(ctx, "GetStreamKey", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
