// Code generated by Kitex v0.13.1. DO NOT EDIT.

package aiservice

import (
	ai "LiveLive/kitex_gen/livelive/ai"
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	AnalyzeAudio(ctx context.Context, req *ai.AnalyzeAudioReq, callOptions ...callopt.Option) (r *ai.AnalyzeAudioResp, err error)
	ChatWithAI(ctx context.Context, req *ai.ChatWithAIReq, callOptions ...callopt.Option) (r *ai.ChatWithAIResp, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kAIServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kAIServiceClient struct {
	*kClient
}

func (p *kAIServiceClient) AnalyzeAudio(ctx context.Context, req *ai.AnalyzeAudioReq, callOptions ...callopt.Option) (r *ai.AnalyzeAudioResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.AnalyzeAudio(ctx, req)
}

func (p *kAIServiceClient) ChatWithAI(ctx context.Context, req *ai.ChatWithAIReq, callOptions ...callopt.Option) (r *ai.ChatWithAIResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ChatWithAI(ctx, req)
}
