// Code generated by Kitex v0.13.1. DO NOT EDIT.

package websocketservice

import (
	websocket "LiveLive/kitex_gen/livelive/websocket"
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	BroadcastToCourse(ctx context.Context, req *websocket.BroadcastToCourseReq, callOptions ...callopt.Option) (r *websocket.BroadcastToCourseResp, err error)
	AggregateAnswers(ctx context.Context, req *websocket.AggregateAnswersReq, callOptions ...callopt.Option) (r *websocket.AggregateAnswersResp, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kWebsocketServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kWebsocketServiceClient struct {
	*kClient
}

func (p *kWebsocketServiceClient) BroadcastToCourse(ctx context.Context, req *websocket.BroadcastToCourseReq, callOptions ...callopt.Option) (r *websocket.BroadcastToCourseResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.BroadcastToCourse(ctx, req)
}

func (p *kWebsocketServiceClient) AggregateAnswers(ctx context.Context, req *websocket.AggregateAnswersReq, callOptions ...callopt.Option) (r *websocket.AggregateAnswersResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.AggregateAnswers(ctx, req)
}
